### ISSUE TITLE
Bluetooth Scanning not functional

### ISSUE THREAD

**Issue by JPG0mez** [JosephHewitt/wardriver_rev3#168]
Been wardriving with this rig for about a couple days and I've yet to get any devices for BLE.

Using version 2.0.12 for the esp32 board on both A & B. After checking the serial monitor, I consistently have 0 devices found even after seting "setActiveScan" to true.

**Comment by JosephHewitt** [comment]
Hi,

What exactly do you see with the serial monitor connected to ESP-B? You should see lines stating the count of BLE found in a scan, followed by the number of WiFi networks found per channel. Is it showing all zeros for both BLE and WiFi? 

You could try flashing ESP-B with the binary release (there's information on how to do this on the repo readme file), this can rule out any issues caused by bad libraries etc on your PC.

I have once seen an ESP32 board with a completely broken radio which was unable to transmit or receive any signals at all but I'm not sure how common that kind of failure is. If the WiFi on your ESP32 is also not working, this may be the issue for you too.

**Comment by JPG0mez** [comment]
I just tried the latest release candidate version "1.2.0rc2" and this is what the serial monitor looks like.

13:55:13.176 -> Scan of channel 11 returned 2
13:55:13.308 -> Scan of channel 14 returned 0
13:55:13.441 -> Scan of channel 1 returned 3
13:55:15.445 -> Devices found: 0
13:55:15.445 -> Scan done!
13:55:15.575 -> Scan of channel 6 returned 0
13:55:15.674 -> Scan of channel 11 returned 1
13:55:15.802 -> Scan of channel 14 returned 0
13:55:15.932 -> Scan of channel 1 returned 2
13:55:17.945 -> Devices found: 0
13:55:17.945 -> Scan done!
13:55:18.042 -> Scan of channel 6 returned 0
13:55:18.173 -> Scan of channel 11 returned 2
13:55:18.362 -> Scan of channel 14 returned 0
13:55:18.410 -> Scan of channel 1 returned 4

Wifi is working on ESP32 B so only BLE is showing zero. I'll try flashing with the binary release and provide an update later today.

**Comment by JPG0mez** [comment]
Think I just got a bad board sadly. Tested out the code against a couple other ESP32's I had laying around and even on board A and it's picking up devices for BLE. Thx for the help.
